//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserve_Invoices_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DevEntities : DbContext
    {
        public DevEntities()
            : base("name=DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReserveInvoices_OpenedDrafts> ReserveInvoices_OpenedDrafts { get; set; }
    
        public virtual ObjectResult<sp_ReserveInvoices_InvoiceLines2_Result> sp_ReserveInvoices_InvoiceLines2(Nullable<int> tOP)
        {
            var tOPParameter = tOP.HasValue ?
                new ObjectParameter("TOP", tOP) :
                new ObjectParameter("TOP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReserveInvoices_InvoiceLines2_Result>("sp_ReserveInvoices_InvoiceLines2", tOPParameter);
        }
    
        public virtual ObjectResult<sp_SAP_BatchAvailability_Result> sp_SAP_BatchAvailability(string itemCode, string whsCode)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_BatchAvailability_Result>("sp_SAP_BatchAvailability", itemCodeParameter, whsCodeParameter);
        }
    
        public virtual ObjectResult<sp_SAP_BinAvailability_Result> sp_SAP_BinAvailability(Nullable<int> batchAbs, string whsCode)
        {
            var batchAbsParameter = batchAbs.HasValue ?
                new ObjectParameter("BatchAbs", batchAbs) :
                new ObjectParameter("BatchAbs", typeof(int));
    
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_BinAvailability_Result>("sp_SAP_BinAvailability", batchAbsParameter, whsCodeParameter);
        }
    
        public virtual ObjectResult<sp_SAP_ShopStockAvailability_Result> sp_SAP_ShopStockAvailability(string itemCode, string whscode)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var whscodeParameter = whscode != null ?
                new ObjectParameter("Whscode", whscode) :
                new ObjectParameter("Whscode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_ShopStockAvailability_Result>("sp_SAP_ShopStockAvailability", itemCodeParameter, whscodeParameter);
        }
    
        public virtual ObjectResult<sp_SAP_WarehouseStockAvailability_Result> sp_SAP_WarehouseStockAvailability(string itemCode)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_WarehouseStockAvailability_Result>("sp_SAP_WarehouseStockAvailability", itemCodeParameter);
        }
    
        public virtual ObjectResult<sp_SAP_BatchAvailability_KS_Result> sp_SAP_BatchAvailability_KS(string itemCode, string whsCode)
        {
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_BatchAvailability_KS_Result>("sp_SAP_BatchAvailability_KS", itemCodeParameter, whsCodeParameter);
        }
    
        public virtual ObjectResult<sp_SAP_BinAvailability_KS_Result> sp_SAP_BinAvailability_KS(Nullable<int> batchAbs, string whsCode)
        {
            var batchAbsParameter = batchAbs.HasValue ?
                new ObjectParameter("BatchAbs", batchAbs) :
                new ObjectParameter("BatchAbs", typeof(int));
    
            var whsCodeParameter = whsCode != null ?
                new ObjectParameter("WhsCode", whsCode) :
                new ObjectParameter("WhsCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_BinAvailability_KS_Result>("sp_SAP_BinAvailability_KS", batchAbsParameter, whsCodeParameter);
        }
    
        public virtual ObjectResult<sp_SAP_GetBPLIdFromWhscode_Result> sp_SAP_GetBPLIdFromWhscode(string whscode)
        {
            var whscodeParameter = whscode != null ?
                new ObjectParameter("Whscode", whscode) :
                new ObjectParameter("Whscode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SAP_GetBPLIdFromWhscode_Result>("sp_SAP_GetBPLIdFromWhscode", whscodeParameter);
        }
    }
}
